Small preview for selected image
Geoalert/mapflow-qgis pull request #111
Opened 2024-06-03 20:02 UTC by odinkomnogim

+ QLabel instead of QGraphicsView

2024-07-03 06:02 UTC, AlexeyTrekin requested changes
Also, what do you think about local storage of image previews? Not necessary right now, but worth discussing, to speed up the preview loading.

2024-07-03 06:02 UTC, AlexeyTrekin commented on mapflow/functional/service/data_catalog.py
> +        ids = self.view.selected_images_ids(limit=limit)
This search by ID looks heavy. Maybe we could rely on the images order (the same in self.images and in the table) and index them just by table positions? And if not, maybe better to store them not in list, but in a dict, like mosaics.

Similarly, when we get "selected_mosaics" we don't need to iterate over ".items", as ID is the key in the dict; we should just use `selected_mosaics = [self.mosaics[id] for id in selected_mosaic_ids]`

2024-08-05 10:15 UTC, AlexeyTrekin requested changes

2024-08-05 10:15 UTC, AlexeyTrekin commented on mapflow/functional/api/data_catalog_api.py
> +        self.dlg.imagePreview.setText("Preview is unavailable")
1. Нужно нормально указать имя и тип аргумента, чтобы можно было поддерживать и развивать, см п.2: `def preview_s_error_handler(self, response: QNetworkReply):`
2. Возможно нужно будет сделать обработку в зависимости от ответа - например, как в стандартном, где по 401 ошибке кидает на логин. Сейчас не нужно, но должно быть возможно, если при тестировании выявится что нужны отдельные случаи.

2024-08-05 12:57 UTC, AlexeyTrekin approved these changes

2024-08-05 17:46 UTC, odinkomnogim commented
New version of this branch ('image_preview_small') is merged into 'feature_catalog_api'

2024-08-05 17:46 UTC, closed without merging