Show taken and free storage
Geoalert/mapflow-qgis pull request #115
Opened 2024-06-18 18:50 UTC by odinkomnogim

2024-07-30 11:52 UTC, AlexeyTrekin requested changes

2024-07-30 11:52 UTC, AlexeyTrekin commented on mapflow/functional/view/data_catalog_view.py
> +        self.dlg.dataLimit.setText("Your data: {taken} MB. Free space: {free} MB".format(taken=round(taken_storage/1000000, 1),
Why /100000, not /1024/1024 ?

2024-07-30 13:55 UTC, odinkomnogim commented on mapflow/functional/view/data_catalog_view.py
> +        self.dlg.dataLimit.setText("Your data: {taken} MB. Free space: {free} MB".format(taken=round(taken_storage/1000000, 1),
Yes, 1 048 576, my bad

2024-08-05 06:51 UTC, AlexeyTrekin approved these changes

2024-08-05 12:29 UTC, closed without merging