Zoom spinBox
Geoalert/mapflow-qgis pull request #136
Opened 2024-09-19 19:11 UTC by odinkomnogim

Add zoom spinbox when variable is True and add 'zoom' to processing params

2024-09-20 07:45 UTC, odinkomnogim commented on mapflow/mapflow.py
> +            self.dlg.dataSourceZoom.valueChanged.connect(lambda value: self.settings.setValue('zoom', str(value)))
Вроде бы всё передаётся правильно, к примеру, старт процессинга с 19 зумом выглядит вот так:
`curl 'https://whitemaps-staging.mapflow.ai/rest/processings' -H 'Content-Type: application/json' -H 'x-plugin-version: 2.6.2' -H 'authorization: Basic ZC5pZ25hdGVua29AZ2VvYWxlcnQuaW86TkZXQmU2bmR5d0lzalVteEprbWg=' -H 'User-Agent: Mozilla/5.0 QGIS/32800/Windows 10 Version 2009'  --data '{"name": "test_zoom_19", "wdId": "30ddfd15-04aa-47f6-9ceb-68ce709fd710", "params": {"data_provider": "Mapbox", **"zoom": "19"**}, "blocks": [{"name": "Classification", "enabled": false}, {"name": "Simplification", "enabled": false}, {"name": "OSM", "enabled": false}], "geometry": {"coordinates": [[[97.0988157865203, 60.800940063405555], [97.11048486366752, 60.800940063405555], [97.11048486366752, 60.804922147531016], [97.0988157865203, 60.804922147531016], [97.0988157865203, 60.800940063405555]]], "type": "Polygon"}, "meta": {"source-app": "qgis", "version": "2.6.2", "source": "mapbox"}, "projectId": "cd4986da-2c93-41a3-8ad7-c2a59d26f29b"}' --compressed`
Но по итогу Source в свойствах слоя выглядит вот так:
`type=xyz&url=https://dev.mapflow.ai/api/v0/cogs/tiles/{z}/{x}/{y}.png?uri=s3://white-maps-rasters/1fcd3363-d2ed-476d-ad7d-63962d8bf109&zmin=0&**zmax=18**`
Я что-то упускаю или в чём-то другом дело?

2024-09-20 14:21 UTC, AlexeyTrekin requested changes
+ add zoom param to ImagerySearch provider as well
+ add zoom param to xyz providers set by user 

(basically anything except for tiff/tif/local)

2024-09-20 14:21 UTC, AlexeyTrekin commented on mapflow/mapflow.py
> +        if self.zoom_selector == 'true':
1. Лучше значение хранить булево, то есть сделать 
```
self.zoom_selector = self.settings.getValue(<key>, "false").lower() == "true"
```
После этого можно обращаться как 
`if self.zoom_selector: `

2024-09-20 14:21 UTC, AlexeyTrekin commented on mapflow/mapflow.py
> +        try:
Remove it?

2024-09-22 20:56 UTC, odinkomnogim commented
> * add zoom param to ImagerySearch provider as well
> * add zoom param to xyz providers set by user
> 
> (basically anything except for tiff/tif/local)

For some reason 'local' also includes user's xyz's. So for now I left only 'tif'

2024-09-23 11:36 UTC, AlexeyTrekin approved these changes
Only minor changes left and may be merged

2024-09-23 11:36 UTC, AlexeyTrekin commented on mapflow/dialogs/main_dialog.py
> +        if QgsSettings().value("variables/zoom_selector", "false").lower() == "true":
use self.settings here, no need to create a new instance!

2024-09-23 11:36 UTC, AlexeyTrekin commented on mapflow/mapflow.py
> +        print (processing_params)
remove the debug prints

2024-09-23 15:23 UTC, merged